name: CI/CD Workflow

on:
  push:
    branches:
      - main  # Adjust as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Adjust as needed

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 700935310038.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t my-image-name .

      - name: Tag Docker image
        run: |
          docker tag my-image-name:latest 700935310038.dkr.ecr.us-east-1.amazonaws.com/my-image-name:latest

      - name: Push Docker image to ECR
        run: |
          docker push 700935310038.dkr.ecr.us-east-1.amazonaws.com/my-image-name:latest

      - name: Clean up
        run: |
          docker rmi 700935310038.dkr.ecr.us-east-1.amazonaws.com/my-image-name:latest || true
          docker rmi my-image-name:latest || true
