name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to ECR
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1 # change if necessary
      run: |
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 700935310038.dkr.ecr.us-east-1.amazonaws.com

    - name: Pull Docker images
      run: |
        docker pull 700935310038.dkr.ecr.us-east-1.amazonaws.com/ai-shashank/netflix-catalog:latest
        docker pull 700935310038.dkr.ecr.us-east-1.amazonaws.com/ai-shashank/netflix-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        ssh user@18.212.194.28 "cd ~/PycharmProjects/Final-Assignment_Bootcamp && docker-compose down && docker-compose up -d"
