name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'  # Change if needed
        run: |
          echo "${{ secrets.AWS_ACCESS_KEY_ID }}" | docker login --username AWS --password-stdin 700935310038.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            700935310038.dkr.ecr.us-east-1.amazonaws.com/ai-shashank/netflix-catalog:latest
            700935310038.dkr.ecr.us-east-1.amazonaws.com/ai-shashank/netflix-frontend:latest

      - name: Deploy
        run: |
          docker-compose -f docker-compose.yaml up -d
